/**
 * PROJECTS page copy, extracted verbatim from the Next.js frontend.
 *
 * Sources:
 *   frontend/app/projects/page.tsx                     -> structured-data-section,
 *                                                         hero-section (cards),
 *                                                         portfolio-tabs-section,
 *                                                         analysis-tab-section,
 *                                                         pipeline-tab-section,
 *                                                         eligibility-cta-section,
 *                                                         next-steps-section
 *   frontend/components/GlassHero.tsx                  -> hero-section (breadcrumb)
 *   frontend/components/projects/PipelineConsole.tsx   -> pipeline-console-section
 *   frontend/components/projects/FootprintMap.tsx      -> footprint-map-section
 *   frontend/components/projects/LGAModal.tsx          -> lga-modal-section
 *   frontend/lib/mapData.ts                            -> footprint-map-section
 *                                                         (states, LGAs, legend,
 *                                                          LGA project records)
 *
 * This is a dynamic-zone payload: every entry carries a `__component` key and
 * the array order matches the render order in frontend/app/projects/page.tsx.
 *
 * Strings that the frontend derives at runtime (the label-keyed stat box
 * descriptions, the pipeline metric card labels/descriptions, the totals row
 * suffixes, status pill text) are written out here as explicit fields so no
 * user-facing copy is left hardcoded.
 */

import { nigeriaMapSvg } from './about-map-svg';

const META_DESCRIPTION =
  'Browse our catalog of local currency de-risked clean energy projects in Nigeria.';

const HERO_IMAGE =
  'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=1200&auto=format&fit=crop';
const SOLAR_IMAGE =
  'https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=800&auto=format&fit=crop';
const AGRO_IMAGE =
  'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800&auto=format&fit=crop';
const TELECOM_IMAGE =
  'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=800&auto=format&fit=crop';
const ACOB_IMAGE =
  'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=800&auto=format&fit=crop';

/** PipelineConsole.tsx:390 / :518 — decorative column backdrops under a colour wash. */
const CONSOLE_LEFT_IMAGE =
  'https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=1200&auto=format&fit=crop';
const CONSOLE_RIGHT_IMAGE =
  'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=1200&auto=format&fit=crop';

/** PipelineConsole.tsx:111-118 SDG_METADATA bgImage, keyed by SDG number. */
const SDG_IMAGES: Record<number, string> = {
  7: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=400&auto=format&fit=crop',
  // Replaces photo-1521791136368, which Unsplash removed (HTTP 404).
  8: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=400&auto=format&fit=crop',
  9: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?q=80&w=400&auto=format&fit=crop',
  11: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=400&auto=format&fit=crop',
  13: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=400&auto=format&fit=crop',
  17: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=400&auto=format&fit=crop',
};

/** Hotspot Network telecom footprint — identical across its 22 states. */
const hotspotState = (stateMapId: string) => ({
  stateMapId,
  projectName: 'Hotspot Network',
  capacity: '15kW (Site Average)',
  funding: '₦43.4m (Site Share)',
  sdgs: '9, 13',
  category: 'Telecoms',
  status: 'Operational',
});

/** Solar-as-a-Service telecom site — the shape repeated across LGA records. */
const telecomSite = (
  developer: string,
  community: string,
  state: string,
  lga: string
) => ({
  developer,
  community,
  state,
  lga,
  projectType: 'Solar as a Service for Telecom Towers',
  puePotential: 0,
  enumerators: 0,
});

export const projectsSections = [
  {
    __component: 'projects-page.structured-data-section' as const,
    pageTitle: 'Projects & portfolio footprint | CFBF',
    metaDescription: META_DESCRIPTION,
    dcTitle: 'Projects portfolio - climate finance blending facility',
    dcCreator: 'NoLimitBuzz',
    dcSubject: 'Solar Grid, Telecoms Solarization, Agro-Processing, Green Bonds',
    dcDescription:
      'Directory of active clean energy infrastructure projects in Nigeria.',
    dcPublisher: 'Climate Finance Blending Facility',
    dcLanguage: 'en',
    dcCoverageSpatial: 'Nigeria',
    dcType: 'Collection of Case Studies',
    jsonLdType: 'CollectionPage',
    jsonLdName: 'Projects Portfolio | Climate Finance Blending Facility',
    jsonLdDescription:
      'Directory of active clean energy infrastructure projects de-risked and co-financed by the Climate Finance Blending Facility in Nigeria.',
    jsonLdUrl: 'https://climatesupportfacility.org/projects',
    jsonLdPublisherName: 'Climate Finance Blending Facility (CFBF)',
  },

  {
    __component: 'projects-page.hero-section' as const,
    breadcrumbLabel: 'projects',
    eyebrow: 'Proven results',
    headingPartOne: 'Portfolio ',
    headingHighlight: 'performance',
    description:
      'The Climate Finance Blending Facility (CFBF) deploys strategic first-loss co-financing to de-risk private commercial capital, mobilizing local funding to power clean energy and create sustainable jobs.',
    backgroundImage: HERO_IMAGE,
    backgroundImage_alt_text: 'Hero banner',
    stats: [
      {
        label: 'Capacity installed',
        value: '4.02',
        unit: 'MW',
        description:
          'installed green capacity de-risked by first-loss co-financing.',
        sdgBadge: 'SDG 7',
      },
      {
        label: 'Emissions avoided',
        value: '7,500+',
        unit: 'tCO₂e',
        description:
          'tonnes of carbon emissions mitigated annually across our portfolio.',
        sdgBadge: 'SDG 13',
      },
      {
        label: 'Job creation',
        value: '5,780+',
        unit: '',
        description: 'sustainable jobs facilitated in local communities.',
        sdgBadge: 'SDG 8',
      },
      {
        label: 'Connections powered',
        value: '39,438',
        unit: '',
        description:
          'projected household and SME connections powered across Nigeria.',
        sdgBadge: 'SDG 7',
      },
      {
        label: 'Capital deployed',
        value: '₦7.86B+',
        unit: '',
        description:
          'mobilized from institutional investors and pension funds into the real economy.',
        sdgBadge: 'SDG 9',
      },
    ],
  },

  {
    __component: 'projects-page.portfolio-tabs-section' as const,
    eyebrow: 'Portfolio',
    headingPartOne: 'Our footprint ',
    headingHighlight: 'in Nigeria',
    body: 'Collectively, renewable energy projects located in 35 states across the six geo-political zones in Nigeria have been approved for co-financing by the Facility.',
    tabs: [
      { label: 'Project Pipeline' },
      { label: 'Project Analysis' },
      { label: 'National Footprint' },
    ],
  },

  {
    __component: 'projects-page.analysis-tab-section' as const,
    tableHeading: 'Portfolio Transactions Performance',
    downloadLabel: 'Download Impact Report',
    downloadHref: '/download.pdf',
    totalsRowLabel: 'Total Portfolio',
    totalsConnectionsSuffix: '+ 120 Sites',
    capacityUnit: 'kW',
    ghgUnit: 't/yr',
    statusOperationalLabel: 'Operational',
    statusUnderConstructionLabel: 'Under Construction',
    statBoxes: [
      {
        label: 'Capacity installed',
        value: '4.02',
        unit: 'MW',
        description: 'installed clean generating capacity co-financed.',
      },
      {
        label: 'Emissions avoided',
        value: '7,500+',
        unit: 'tCO₂e',
        description: 'tonnes of annual carbon emissions mitigated.',
      },
      {
        label: 'Jobs created',
        value: '5,780+',
        unit: '',
        description: 'sustainable employment opportunities facilitated.',
      },
      {
        label: 'Connections powered',
        value: '39,438',
        unit: '',
        description: 'projected household and SME connections powered.',
      },
    ],
    columnHeads: [
      { label: 'Project Name' },
      { label: 'Capacity' },
      { label: 'Capital Mobilised' },
      { label: 'Connections' },
      { label: 'Jobs Created' },
      { label: 'GHG Reduced' },
      { label: 'Status' },
    ],
  },

  {
    __component: 'projects-page.pipeline-tab-section' as const,
    filterBannerPrefix: 'Filtering by region:',
    stateSuffix: 'State',
    clearFilterLabel: 'Clear State Filter',
    projectIdPrefix: '/ ',
    challengeLabel: 'Challenge & solution',
    financialCloseLabel: 'Financial close:',
    privateCapitalLabel: 'Private capital:',
    sdgGoalsLabel: 'Aligned SDG goals',
    detailsLinkLabel: 'Explore Project Details',
    categories: [
      { label: 'All' },
      { label: 'Solar Grid' },
      { label: 'Telecoms' },
      { label: 'Agro-Processing' },
    ],
    projects: [
      {
        projectId: '01',
        title: 'First Electric Power and Automation Services',
        location: 'Gombe, Nasarawa & Ondo States',
        year: '2025',
        capital: '₦1.70b',
        capacity: '725KW',
        category: 'Solar Grid',
        connections: '5,156',
        jobs: '616',
        ghg: '762 Tonnes',
        status: 'Under Construction',
        image: SOLAR_IMAGE,
        image_alt_text: 'First Electric Nigeria Limited',
        desc: 'Mesh grid networks connecting rural households and SMEs across three states.',
        problem:
          'Lack of grid access in agricultural communities leading to low economic productivity.',
        solution:
          'Construction of 725kWp total capacity mesh grid electricity networks in 20 communities.',
        impact:
          'Connecting 5,156 households and creating over 616 local construction and operational jobs.',
        sdgs: '7, 13',
      },
      {
        projectId: '02',
        title: 'CEESOLAR Energy Limited',
        location: 'Cross River State',
        year: '2025',
        capital: '₦1.70b',
        capacity: '760KW',
        category: 'Solar Grid',
        connections: '3,597',
        jobs: '561',
        ghg: '737 Tonnes',
        status: 'Under Construction',
        image: SOLAR_IMAGE,
        image_alt_text: 'CEESOLAR Energy Limited',
        desc: 'Green Finance for Off-Grid Rural Electrification in four communities.',
        problem:
          'Lack of grid infrastructure in remote areas of Cross River, relying heavily on wood fuel and generators.',
        solution:
          'Installation of 760kWp solar-hybrid mini-grids with high-capacity storage.',
        impact:
          'Powering households, small retailers, and agricultural processors; reducing GHG by 737 tonnes per year.',
        sdgs: '7, 13',
      },
      {
        projectId: '03',
        title: 'Prado Power Energy Limited',
        location: 'Akwa-Ibom & Benue States',
        year: '2024',
        capital: '₦1.95b',
        capacity: '850kW',
        category: 'Agro-Processing',
        connections: '15,801',
        jobs: '740',
        ghg: '893 Tonnes',
        status: 'Under Construction',
        image: AGRO_IMAGE,
        image_alt_text: 'Prado Power Energy Limited',
        desc: 'Solar hybrid mini-grids powering agricultural value chain hubs.',
        problem:
          'Post-harvest agricultural losses and lack of cold storage for rural farming cooperatives.',
        solution:
          '850kWp total capacity solar hybrid grids connecting farms, processing plants, and residential clusters.',
        impact:
          'De-risking local food supply chains, connecting 15,801 households, and creating 740 productive jobs.',
        sdgs: '7, 8, 9',
      },
      {
        projectId: '04',
        title: 'Hotspot Network Limited',
        location: '22 States in Nigeria',
        year: '2023',
        capital: '₦955m',
        capacity: '324kW',
        category: 'Telecoms',
        connections: '120 Sites',
        jobs: '720',
        ghg: '8.34 Tonnes',
        status: 'Operational',
        image: TELECOM_IMAGE,
        image_alt_text: 'Hotspot Network Limited',
        desc: 'Green Finance for Sustainable Rural Telephony networks.',
        problem:
          'Off-grid telecommunication towers in rural communities rely on diesel generators, releasing heavy CO2.',
        solution:
          'Solarization of 120 base stations across 22 states using highly efficient panels.',
        impact:
          'Providing continuous rural connectivity, saving carbon emissions, and creating 720 telecom support jobs.',
        sdgs: '9, 13',
      },
      {
        projectId: '05',
        title: 'Darway Coast Limited',
        location: 'Rivers & Abia States',
        year: '2022',
        capital: '₦800m',
        capacity: '526kW',
        category: 'Solar Grid',
        connections: '7,711',
        jobs: '2,296',
        ghg: '4,856 Tonnes',
        status: 'Operational',
        image: SOLAR_IMAGE,
        image_alt_text: 'Darway Coast Limited',
        desc: 'Isolated solar mini-grids for underserved southern communities.',
        problem:
          'Lack of clean, reliable energy for coastal fish drying and local enterprise in southern Riverine zones.',
        solution:
          '526kWp solar grids using prepaid smart meters and remote monitoring systems.',
        impact:
          'Powering 7,711 connections, replacing diesel gensets, and boosting local riverine commerce.',
        sdgs: '7, 13',
      },
      {
        projectId: '06',
        title: 'ACOB Lightning Technology Limited',
        location: 'Edo & Ondo States',
        year: '2023',
        capital: '₦755m',
        capacity: '335kW',
        category: 'Solar Grid',
        connections: '3,597',
        jobs: '868',
        ghg: '352 Tonnes',
        status: 'Operational',
        image: ACOB_IMAGE,
        image_alt_text: 'ACOB Lightning Technology Limited',
        desc: 'Off-grid rural electrification for agricultural hubs.',
        problem:
          'Energy poverty in rural cocoa-farming communities with zero electricity access.',
        solution:
          '335kWp solar-hybrid installations with local commercial distribution networks.',
        impact:
          'De-risked electricity access for 3,597 cocoa farmers, saving 352 tonnes of carbon annually.',
        sdgs: '7, 8, 13',
      },
    ],
    sdgDefinitions: [
      { number: '7', name: 'Affordable & Clean Energy' },
      { number: '8', name: 'Decent Work & Growth' },
      { number: '9', name: 'Industry, Innovation & Infrastructure' },
      { number: '13', name: 'Climate Action' },
    ],
    stateProjects: [
      {
        stateMapId: 'gombe',
        projectName: 'First Electric',
        capacity: '240kW (Regional Share)',
        funding: '₦560m',
        sdgs: '7, 13',
        category: 'Solar Grid',
        status: 'Under Construction',
      },
      {
        stateMapId: 'nasarawa',
        projectName: 'First Electric',
        capacity: '240kW (Regional Share)',
        funding: '₦560m',
        sdgs: '7, 13',
        category: 'Solar Grid',
        status: 'Under Construction',
      },
      {
        stateMapId: 'edo',
        projectName: 'ACOB Lightning',
        capacity: '165kW (Regional Share)',
        funding: '₦370m',
        sdgs: '7, 8, 13',
        category: 'Solar Grid',
        status: 'Operational',
      },
      {
        stateMapId: 'ondo',
        projectName: 'First Electric',
        capacity: '245kW (Regional Share)',
        funding: '₦580m',
        sdgs: '7, 13',
        category: 'Solar Grid',
        status: 'Under Construction',
      },
      {
        stateMapId: 'ondo',
        projectName: 'ACOB Lightning',
        capacity: '170kW (Regional Share)',
        funding: '₦385m',
        sdgs: '7, 8, 13',
        category: 'Solar Grid',
        status: 'Operational',
      },
      {
        stateMapId: 'cross-river',
        projectName: 'CEESOLAR Energy',
        capacity: '760kW',
        funding: '₦1.70b',
        sdgs: '7, 13',
        category: 'Solar Grid',
        status: 'Under Construction',
      },
      {
        stateMapId: 'akwa-ibom',
        projectName: 'Prado Power',
        capacity: '425kW (Regional Share)',
        funding: '₦975m',
        sdgs: '7, 8, 9',
        category: 'Agro-Processing',
        status: 'Under Construction',
      },
      {
        stateMapId: 'benue',
        projectName: 'Prado Power',
        capacity: '425kW (Regional Share)',
        funding: '₦975m',
        sdgs: '7, 8, 9',
        category: 'Agro-Processing',
        status: 'Under Construction',
      },
      {
        stateMapId: 'rivers',
        projectName: 'Darway Coast',
        capacity: '263kW (Regional Share)',
        funding: '₦400m',
        sdgs: '7, 13',
        category: 'Solar Grid',
        status: 'Operational',
      },
      {
        stateMapId: 'abia',
        projectName: 'Darway Coast',
        capacity: '263kW (Regional Share)',
        funding: '₦400m',
        sdgs: '7, 13',
        category: 'Solar Grid',
        status: 'Operational',
      },
      hotspotState('kaduna'),
      hotspotState('kano'),
      hotspotState('oyo'),
      hotspotState('bauchi'),
      hotspotState('katsina'),
      hotspotState('jigawa'),
      hotspotState('sokoto'),
      hotspotState('zamfara'),
      hotspotState('kebbi'),
      hotspotState('kogi'),
      hotspotState('kwara'),
      hotspotState('taraba'),
      hotspotState('adamawa'),
      hotspotState('borno'),
      hotspotState('yobe'),
      hotspotState('plateau'),
      hotspotState('niger'),
      hotspotState('ekiti'),
      hotspotState('osun'),
      hotspotState('ogun'),
      hotspotState('lagos'),
      hotspotState('fct'),
    ],
  },

  {
    __component: 'projects-page.pipeline-console-section' as const,
    eyebrow: 'Consolidated Dealflow',
    headingPartOne: 'Facility Pipeline ',
    headingHighlight: 'Status',
    body: 'Browse live consolidated aggregates of our clean energy pipelines, mandated capital transactions, and forecasted developmental impact numbers de-risked by our concessional guarantee structures.',
    selectStageLabel: 'Select Pipeline Stage',
    usdUnitLabel: 'm USD',
    sdgFrameworksLabel: 'Aligned UN SDG Frameworks',
    toggleTotalLabel: 'Total Pipeline',
    toggleMandatedLabel: 'Mandated Deals',
    metricsHeader: '/ EXPECTED IMPACT METRICS',
    businessModelsHeader: '/ BUSINESS MODELS DISTRIBUTION',
    metricsSubcopy:
      'Forecasted socio-economic and environmental outputs expected from the active pipeline deals de-risked by our concessional guarantee structures.',
    businessModelsSubcopy:
      'Distribution of blended finance transactions categorized by developer business models mandated by the facility.',
    tableHeadSector: 'DRE Business Model',
    tableHeadProjects: 'Projects',
    tableHeadPipelineNgn: "Pipeline (NGN'B)",
    tableHeadMandatedNgn: "Mandated (NGN'B)",
    tableHeadDealSize: 'Deal Size (%)',
    footerLabel: 'Total Portfolio',
    footerProjects: '71',
    footerTotalPipeline: '948.20',
    footerTotalMandated: '294.28',
    footerPercent: '100%',
    businessModelsMandatedUsd: '213.2',
    businessModelsMandatedNgn: '294.28B NGN EQUIV',
    metricLabels: [
      {
        label: 'Projected Connections',
        unit: '',
        description: 'projected household and SME connections powered.',
      },
      {
        label: 'Projected Capacity',
        unit: '',
        description: 'installed clean generating capacity co-financed.',
      },
      {
        label: 'Communities',
        unit: '',
        description: 'underserved administrative areas connected.',
      },
      {
        label: 'Jobs to be Created',
        unit: '',
        description: 'sustainable employment opportunities facilitated.',
      },
      {
        label: 'GHG Emissions Reduced',
        unit: 'tCO₂e/yr',
        description: 'tonnes of annual carbon emissions mitigated.',
      },
      {
        label: 'Private Capital Mobilised',
        unit: '',
        description: 'local private currency co-investment mobilized.',
      },
    ],
    stages: [
      {
        stageId: 'business-models',
        label: 'Business Models',
        title: 'BUSINESS MODELS',
        usdVal: '687.3',
        ngnVal: '948.20B NGN EQUIV',
        desc: 'Blended finance pipeline sector distribution categorized by clean energy off-grid developer business models de-risked and mandated by the Facility.',
        sdgs: '7, 8, 9, 11, 13, 17',
      },
      {
        stageId: 'project-pipeline',
        label: 'Project Pipeline',
        title: 'PROJECT PIPELINE',
        usdVal: '687.3',
        ngnVal: '948.20B NGN EQUIV',
        desc: 'The 72 Projects Pipeline reports on expected energy access connections, clean generating capacity, employment opportunities, and carbon mitigation aligned to UN Sustainable Development Goals (SDGs).',
        sdgs: '7, 8, 9, 11, 13, 17',
        metrics: {
          connections: '731,083',
          connectionsLabel: '',
          capacity: '166.09 MWp',
          communities: '5,287',
          communitiesLabel: '',
          jobs: '162,600.5',
          ghg: '314,681.09',
          capital: '₦46.46B',
          capitalSub: 'USD 33.7 Mln',
        },
      },
      {
        stageId: 'credit-approved',
        label: 'Credit Approved Pipeline',
        title: 'CREDIT APPROVED PIPELINE',
        usdVal: '38.8',
        ngnVal: '53.55B NGN EQUIV',
        desc: 'The 14 Credit Approved Pipeline Projects have passed final facility guarantees and credit criteria, gearing up for commercial close and local capital drawdown.',
        sdgs: '7, 8, 9, 11, 13, 17',
        metrics: {
          connections: '79,786',
          connectionsLabel: '',
          capacity: '22.50 MW',
          communities: '62',
          communitiesLabel: '',
          jobs: '20,035',
          ghg: '81,366.00',
          capital: '₦9.6B',
          capitalSub: 'USD 7.0 Mln',
        },
      },
      {
        stageId: 'closed',
        label: 'Closed Projects',
        title: 'CLOSED PROJECTS',
        usdVal: '17.7',
        ngnVal: '24.36B NGN EQUIV',
        desc: 'The 4 Closed Projects have successfully achieved financial close, fully drawn local pension-backed funds, and are active in construction or operations.',
        sdgs: '7, 8, 9, 11, 13, 17',
        metrics: {
          connections: '51,131',
          connectionsLabel: '',
          capacity: '7.49 MWp',
          communities: '169',
          communitiesLabel: '',
          jobs: '18,699',
          ghg: '12,510.90',
          capital: '₦11.4B',
          capitalSub: 'USD 8.3 Mln',
        },
      },
      {
        stageId: 'urban-pipeline',
        label: 'Urban Pipeline Projects',
        title: 'URBAN PIPELINE PROJECTS',
        usdVal: '54.6',
        ngnVal: '84.40B NGN EQUIV',
        desc: 'The 7 Urban Pipeline Projects address energy reliability in municipalities, focusing on commercial utility scaling and private capital integration.',
        sdgs: '7, 8, 9, 11, 13, 17',
        metrics: {
          connections: '3,350',
          connectionsLabel: '',
          capacity: '27.68 MW',
          communities: '0',
          communitiesLabel: 'Communities Impacted',
          jobs: '1,820',
          ghg: '251.89',
          capital: '₦0.0B',
          capitalSub: 'USD 0.0 Mln',
        },
      },
      {
        stageId: 'urban-credit-approved',
        label: 'Urban Credit Approved Pipeline',
        title: 'URBAN CREDIT APPROVED',
        usdVal: '5.95',
        ngnVal: '3.80B NGN EQUIV',
        desc: 'The 2 Urban Credit Approved Projects focus on commercial microgrid integrations within dense population hubs and local government area clusters.',
        sdgs: '7, 8, 9, 11, 13, 17',
        metrics: {
          connections: '1,213',
          connectionsLabel: 'Households & Businesses',
          capacity: '9.90 MW',
          communities: '12',
          communitiesLabel: 'Local Gov Areas',
          jobs: '1,115',
          ghg: '90.09',
          capital: '₦0.0B',
          capitalSub: 'USD 0.0 Mln',
        },
      },
    ],
    leftBackgroundImage: CONSOLE_LEFT_IMAGE,
    leftBackgroundImage_alt_text: '',
    rightBackgroundImage: CONSOLE_RIGHT_IMAGE,
    rightBackgroundImage_alt_text: '',
    sdgFrameworks: [
      {
        number: '7',
        name: 'Affordable & Clean Energy',
        image: SDG_IMAGES[7],
        image_alt_text: 'Affordable & Clean Energy',
      },
      {
        number: '8',
        name: 'Decent Work & Growth',
        image: SDG_IMAGES[8],
        image_alt_text: 'Decent Work & Growth',
      },
      {
        number: '9',
        name: 'Industry & Infrastructure',
        image: SDG_IMAGES[9],
        image_alt_text: 'Industry & Infrastructure',
      },
      {
        number: '11',
        name: 'Sustainable Cities',
        image: SDG_IMAGES[11],
        image_alt_text: 'Sustainable Cities',
      },
      {
        number: '13',
        name: 'Climate Action',
        image: SDG_IMAGES[13],
        image_alt_text: 'Climate Action',
      },
      {
        number: '17',
        name: 'Partnerships for Goals',
        image: SDG_IMAGES[17],
        image_alt_text: 'Partnerships for Goals',
      },
    ],
    totalPipelineRows: [
      { sector: 'Isolated Mini-Grid', projectsCount: 37, valueNgn: 381.16, percentage: '40.20%' },
      { sector: 'Interconnected Mini-Grid', projectsCount: 5, valueNgn: 32.77, percentage: '3.46%' },
      { sector: 'Mesh Grid', projectsCount: 3, valueNgn: 59.27, percentage: '6.25%' },
      { sector: 'Commercial & Industrial (C & I)', projectsCount: 13, valueNgn: 298.85, percentage: '31.52%' },
      { sector: 'SaaS for Home and Business', projectsCount: 2, valueNgn: 28.6, percentage: '3.02%' },
      { sector: 'Productive Use EaaS', projectsCount: 1, valueNgn: 1.36, percentage: '0.14%' },
      { sector: 'Battery as a Service', projectsCount: 0, valueNgn: 0, percentage: '0.00%' },
      { sector: 'Stand Alone Systems (SAS)', projectsCount: 0, valueNgn: 0, percentage: '0.00%' },
      { sector: 'SaaS for Telecom Towers', projectsCount: 4, valueNgn: 85.04, percentage: '8.97%' },
      { sector: 'E-mobility (2W & 3W)', projectsCount: 6, valueNgn: 61.15, percentage: '6.45%' },
    ],
    mandatedDealRows: [
      { sector: 'Isolated Mini-Grid', projectsCount: 37, valueNgn: 91.39, percentage: '31.06%' },
      { sector: 'Interconnected Mini-Grid', projectsCount: 5, valueNgn: 28.21, percentage: '9.59%' },
      { sector: 'Mesh Grid', projectsCount: 3, valueNgn: 16.27, percentage: '5.53%' },
      { sector: 'Commercial & Industrial (C & I)', projectsCount: 13, valueNgn: 107.95, percentage: '36.68%' },
      { sector: 'SaaS for Home and Business', projectsCount: 2, valueNgn: 1.0, percentage: '0.34%' },
      { sector: 'Productive Use EaaS', projectsCount: 1, valueNgn: 1.36, percentage: '0.46%' },
      { sector: 'Battery as a Service', projectsCount: 0, valueNgn: 0, percentage: '0.00%' },
      { sector: 'Stand Alone Systems (SAS)', projectsCount: 0, valueNgn: 0, percentage: '0.00%' },
      { sector: 'E-mobility (2W & 3W)', projectsCount: 6, valueNgn: 13.06, percentage: '4.44%' },
    ],
  },

  {
    __component: 'projects-page.eligibility-cta-section' as const,
    eyebrow: 'Funding intake',
    headingPartOne: 'Do you have a ',
    headingHighlight: 'clean energy project',
    headingPartTwo: '?',
    body: "Verify your project's compliance against our eligibility checklist, estimate your qualifying scores, and start the blended finance pre-qualification application.",
    ctaLabel: 'Check project eligibility',
    ctaHref: '/eligibility',
    backgroundImage:
      'https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=1200&auto=format&fit=crop',
    backgroundImage_alt_text: 'Clean energy installation background',
  },

  {
    __component: 'projects-page.footprint-map-section' as const,
    eyebrow: 'National Footprint',
    headingPartOne: 'Geographical ',
    headingHighlight: 'Distribution',
    body: 'Off-grid renewable energy and rural telephony projects located across the six geo-political zones in Nigeria, approved for co-financing by the Facility.',
    statesStatLabel: 'States',
    communitiesStatLabel: 'Communities',
    statesColumnLabel: 'States',
    searchPlaceholder: 'Search states…',
    mapLabel: 'Interactive Map',
    mapHint: 'Click a state',
    lgaPanelSuffix: "State (LGA's)",
    lgaEmptyMessage: 'No LGA data found for this state.',
    clearSelectionLabel: 'Clear Selection',
    placeholderTitle: 'Select a State',
    placeholderBody:
      'Click a state from the list or on the map to view its Local Government Areas.',
    // FootprintMap.tsx:257-262 renders the same @svg-maps/nigeria geometry the
    // About page's energy map does; colours are applied at runtime from states[].
    mapSvg: nigeriaMapSvg,
    legend: [
      { label: 'Rural Electrification', color: '#48C0A3', type: 'rural-electrification' },
      { label: 'Rural Telephony', color: '#648CDC', type: 'rural-telephony' },
      { label: 'Rural Electrification & Telephony', color: '#FDB713', type: 'both' },
      { label: 'Mini Grids – Markets', color: '#B4A082', type: 'mini-grids' },
      { label: 'Default', color: '#2d6a4f', type: 'default' },
      { label: 'PUE', color: '#69b44b', type: 'pue' },
      { label: 'Rural Electrification & PUE', color: '#f4845f', type: 'rural-elec-pue' },
    ],
    states: [
      {
        mapId: 'abia',
        name: 'Abia',
        hasProjects: true,
        projectType: 'rural-electrification',
        lgas: [{ name: 'Umunneochi' }, { name: 'Ohafia' }, { name: 'Isuikwuato' }],
      },
      {
        mapId: 'adamawa',
        name: 'Adamawa',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [{ name: 'Hong' }, { name: 'Mubi North' }, { name: 'Demsa' }],
      },
      {
        mapId: 'akwa-ibom',
        name: 'Akwa Ibom',
        hasProjects: true,
        projectType: 'rural-electrification',
        lgas: [
          { name: 'Eket' },
          { name: 'Ikot Ekpene' },
          { name: 'Uyo' },
          { name: 'Essien Udim' },
        ],
      },
      {
        mapId: 'anambra',
        name: 'Anambra',
        hasProjects: true,
        projectType: 'rural-electrification',
        lgas: [
          { name: 'Anambra West' },
          { name: 'Awka South' },
          { name: 'Anaocha' },
          { name: 'Oji River' },
        ],
      },
      {
        mapId: 'bauchi',
        name: 'Bauchi',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: "Jam'are" },
          { name: 'Tafawa-Balewa' },
          { name: 'Shira' },
          { name: 'Giade' },
          { name: "Jama'are" },
          { name: 'Katagum' },
          { name: 'Ningi' },
          { name: 'Ganjuwa' },
          { name: 'Warji' },
          { name: 'Itas' },
          { name: 'Toro' },
          { name: 'Darazo' },
          { name: 'Bauchi' },
        ],
      },
      {
        mapId: 'bayelsa',
        name: 'Bayelsa',
        hasProjects: true,
        projectType: 'rural-electrification',
        lgas: [{ name: 'Southern Ijaw' }, { name: 'Sagbama' }],
      },
      {
        mapId: 'benue',
        name: 'Benue',
        hasProjects: true,
        projectType: 'both',
        lgas: [
          { name: 'Apa' },
          { name: 'Ohimini' },
          { name: 'Bukuru' },
          { name: 'Ushongo' },
          { name: 'Guma' },
          { name: 'Oju' },
          { name: 'Gboko' },
          { name: 'Obi' },
          { name: 'Kwande' },
          { name: 'Konshisha' },
          { name: 'Ukum' },
          { name: 'Gwer West' },
          { name: 'Katsina-Ala' },
          { name: 'Oshongo' },
        ],
      },
      {
        mapId: 'borno',
        name: 'Borno',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [{ name: 'Hawul' }],
      },
      {
        mapId: 'cross-river',
        name: 'Cross River',
        hasProjects: true,
        projectType: 'rural-electrification',
        lgas: [
          { name: 'Akampa' },
          { name: 'Obrubra' },
          { name: 'Ikom' },
          { name: 'Boki' },
          { name: 'Obubra' },
          { name: 'Yala' },
          { name: 'Akamkpa' },
          { name: 'Biase' },
          { name: 'Ogoja' },
        ],
      },
      {
        mapId: 'delta',
        name: 'Delta',
        hasProjects: true,
        projectType: 'rural-electrification',
        lgas: [{ name: 'Ika South' }, { name: 'Uvwie' }, { name: 'Oshimili South' }],
      },
      {
        mapId: 'ebonyi',
        name: 'Ebonyi',
        hasProjects: true,
        projectType: 'rural-electrification',
        lgas: [{ name: 'Izzi' }, { name: 'Ohaukwu' }, { name: 'Ohaozara' }],
      },
      {
        mapId: 'edo',
        name: 'Edo',
        hasProjects: true,
        projectType: 'rural-electrification',
        lgas: [
          { name: 'Ovia South East' },
          { name: 'Egor' },
          { name: 'Ovia South West' },
          { name: 'Ikpoba-Okha' },
        ],
      },
      {
        mapId: 'ekiti',
        name: 'Ekiti',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [{ name: 'Ikole' }, { name: 'Ado-Ekiti' }],
      },
      {
        mapId: 'enugu',
        name: 'Enugu',
        hasProjects: true,
        projectType: 'rural-electrification',
        lgas: [{ name: 'Oji River' }, { name: 'Anaocha' }],
      },
      {
        mapId: 'fct',
        name: 'Federal Capital Territory',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Kuje' },
          { name: 'Bwari' },
          { name: 'Kwali' },
          { name: 'Gwagwalada' },
          { name: 'Abaji' },
          { name: 'Karu' },
          { name: 'AMAC' },
          { name: 'Abuja' },
        ],
      },
      {
        mapId: 'gombe',
        name: 'Gombe',
        hasProjects: true,
        projectType: 'rural-electrification',
        lgas: [
          { name: 'Akko' },
          { name: 'Dukku' },
          { name: 'Gombe' },
          { name: 'Kaltungo' },
          { name: 'Balanga' },
          { name: 'Biliri' },
          { name: 'Yamaltu/Deba' },
          { name: 'Kwami' },
          { name: 'Shongom' },
          { name: 'Billiri' },
          { name: 'Nafada' },
        ],
      },
      {
        mapId: 'imo',
        name: 'Imo',
        hasProjects: true,
        projectType: 'rural-electrification',
        lgas: [{ name: 'Owerri' }, { name: 'Ohai-Egbema' }],
      },
      {
        mapId: 'jigawa',
        name: 'Jigawa',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Babura' },
          { name: 'Gwaram' },
          { name: 'Miga' },
          { name: 'Kaugama' },
          { name: 'Auyo' },
          { name: 'Guri' },
          { name: 'Garki' },
          { name: 'Kiri Kasama' },
          { name: 'Bade' },
          { name: 'Kazaure' },
          { name: 'Sule Tankakar' },
          { name: 'Birnin Kudu' },
          { name: 'Dankgwanki' },
          { name: 'Jahun' },
          { name: 'Kiyawa' },
          { name: 'Kafin Hausa' },
          { name: 'Ringim' },
          { name: 'Dutse' },
        ],
      },
      {
        mapId: 'kaduna',
        name: 'Kaduna',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Lere' },
          { name: 'Kagarko' },
          { name: 'Sanga' },
          { name: 'Kudan' },
          { name: 'Kachia' },
          { name: 'Zangon Kataf' },
          { name: 'Ikara' },
          { name: 'Kauru' },
          { name: 'Giwa' },
          { name: 'Maru' },
          { name: 'Birnin Gwari' },
          { name: 'Bichi' },
          { name: "Jema'a" },
          { name: 'Igabi' },
          { name: 'Gwagwada' },
          { name: 'Makarfi' },
          { name: 'Kaduna North' },
          { name: 'Kaduna South' },
          { name: 'Kubau' },
          { name: 'Sabon Gari' },
          { name: 'Zaria' },
        ],
      },
      {
        mapId: 'kano',
        name: 'Kano',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Dambatta' },
          { name: 'Rogo' },
          { name: 'Gezawa' },
          { name: 'Tudun Wada' },
          { name: 'Bichi' },
          { name: 'Gabasawa' },
          { name: 'Kunchi' },
          { name: 'Kibiya' },
          { name: 'Rano' },
          { name: 'Sumaila' },
          { name: 'Gaya' },
          { name: 'Bagwai' },
          { name: 'Kiru' },
          { name: 'Garki' },
          { name: 'Karaye' },
          { name: 'Wudil' },
          { name: 'Warawa' },
          { name: 'Ajingi' },
          { name: 'Kura' },
          { name: 'Garun Malam' },
        ],
      },
      {
        mapId: 'katsina',
        name: 'Katsina',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Daura' },
          { name: 'Baure' },
          { name: 'Kankia' },
          { name: 'Kankara' },
          { name: 'Kusada' },
          { name: 'Safana' },
          { name: 'Musawa' },
          { name: 'Sandamu' },
          { name: 'Jibia' },
          { name: 'Dutsin Ma' },
          { name: 'Zango' },
          { name: 'Kaita' },
          { name: 'Ingawa' },
          { name: 'Bindawa' },
          { name: 'Charanchi' },
          { name: 'Bakori' },
          { name: 'Dan Musa' },
          { name: 'Funtua' },
          { name: 'Katsina' },
          { name: 'Malumfashi' },
          { name: 'Matazu' },
        ],
      },
      {
        mapId: 'kebbi',
        name: 'Kebbi',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Alijero' },
          { name: 'Bunza' },
          { name: 'Jega' },
          { name: 'Birnin Kebbi' },
          { name: 'Suru' },
          { name: 'Augie' },
        ],
      },
      {
        mapId: 'kogi',
        name: 'Kogi',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Dekina' },
          { name: 'Yagba West' },
          { name: 'Ijumu' },
          { name: 'Ankpa' },
          { name: 'Olamaboro' },
          { name: 'Lokoja' },
          { name: 'Ibaji' },
          { name: 'Kabba/Bunu' },
          { name: 'Omala' },
          { name: 'Bassa' },
          { name: 'Ofu' },
          { name: 'Igala-Mela/Odolu' },
        ],
      },
      {
        mapId: 'kwara',
        name: 'Kwara',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [{ name: 'Asa' }, { name: 'Baruten' }, { name: 'Edu' }, { name: 'Gwanara' }],
      },
      {
        mapId: 'lagos',
        name: 'Lagos',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Ikorodu' },
          { name: 'Ikeja' },
          { name: 'Ajeromi Ifelodun' },
          { name: 'Lagos Island' },
          { name: 'Eti Osa' },
          { name: 'Lagos Mainland' },
        ],
      },
      {
        mapId: 'nasarawa',
        name: 'Nasarawa',
        hasProjects: true,
        projectType: 'both',
        lgas: [
          { name: 'Awe' },
          { name: 'Karu' },
          { name: 'Toto' },
          { name: 'Nasarawa' },
          { name: 'Zangon Kataf' },
          { name: 'Lafia' },
          { name: 'Akwanga' },
          { name: 'Nassarawa Egon' },
        ],
      },
      {
        mapId: 'niger',
        name: 'Niger',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Agwara' },
          { name: 'Lavun/Mokwa' },
          { name: 'Birnin Maza/Tashibo' },
          { name: 'Magama' },
          { name: 'Wushishi' },
          { name: 'Mokwa' },
          { name: 'Rafi' },
          { name: 'Edati' },
          { name: 'Mashegu' },
          { name: 'Mariga' },
          { name: 'Rijau' },
          { name: 'Borgu' },
          { name: 'Gbako' },
          { name: 'Paikoro' },
          { name: 'Munya' },
          { name: 'Katcha' },
          { name: 'Lavun' },
        ],
      },
      {
        mapId: 'ogun',
        name: 'Ogun',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Yewa North' },
          { name: 'Odeda' },
          { name: 'Ado-Odo/Ota' },
          { name: 'Obafemi Owode' },
          { name: 'Epe' },
          { name: 'Yewa' },
          { name: 'Ikenne' },
          { name: 'Abeokuta South' },
          { name: 'Ijebu Ode' },
        ],
      },
      {
        mapId: 'ondo',
        name: 'Ondo',
        hasProjects: true,
        projectType: 'both',
        lgas: [
          { name: 'Ondo' },
          { name: 'Odigbo' },
          { name: 'Irele' },
          { name: 'Akure North' },
          { name: 'Ese Odo' },
          { name: 'Ondo East' },
          { name: 'Meoluji/Oke Igbo' },
          { name: 'Oke Igbo' },
          { name: 'Akoko North-West' },
          { name: 'Idanre' },
          { name: 'Akure South' },
        ],
      },
      {
        mapId: 'osun',
        name: 'Osun',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Isokan' },
          { name: 'Ilesha West' },
          { name: 'Ayedire' },
          { name: 'Iwo' },
        ],
      },
      {
        mapId: 'oyo',
        name: 'Oyo',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Iseyin' },
          { name: 'Ido' },
          { name: 'Saki East' },
          { name: 'Ibarapa Central' },
          { name: 'Afijio' },
          { name: 'Ibarapa East' },
          { name: 'Ogbomoso' },
          { name: 'Surulere' },
          { name: 'Itesiwaju' },
          { name: 'Ibadan North' },
        ],
      },
      {
        mapId: 'plateau',
        name: 'Plateau',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [{ name: 'Wase' }, { name: 'Shendam' }, { name: 'Langtang South' }],
      },
      {
        mapId: 'rivers',
        name: 'Rivers',
        hasProjects: true,
        projectType: 'rural-electrification',
        lgas: [
          { name: 'Ahoada East' },
          { name: 'Bonny' },
          { name: 'Degema' },
          { name: 'Eleme' },
          { name: 'Ikwerre' },
          { name: 'Khana' },
          { name: 'Obio/Akpor' },
          { name: 'Tai' },
        ],
      },
      {
        mapId: 'sokoto',
        name: 'Sokoto',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Sabon Birni' },
          { name: 'Shagari' },
          { name: 'Illela' },
          { name: 'Gada' },
          { name: 'Goronyo' },
          { name: 'Augie' },
          { name: 'Rabah' },
          { name: 'Birdawa/Sabon Birni' },
        ],
      },
      {
        mapId: 'taraba',
        name: 'Taraba',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Bau' },
          { name: 'Ardo-Kola' },
          { name: 'Sardauna' },
          { name: 'Wukari' },
          { name: 'Bali' },
        ],
      },
      {
        mapId: 'yobe',
        name: 'Yobe',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [{ name: 'Jakusko' }, { name: 'Fika' }],
      },
      {
        mapId: 'zamfara',
        name: 'Zamfara',
        hasProjects: true,
        projectType: 'rural-telephony',
        lgas: [
          { name: 'Bukkuyum' },
          { name: 'Maru' },
          { name: 'Tsafe' },
          { name: 'Birnin Magaji/Kiyaw' },
          { name: 'Zurmi' },
          { name: 'Bakura' },
          { name: 'Bungudun' },
        ],
      },
    ],
    lgaProjects: [
      // Nasarawa - First Electric
      {
        developer: 'ACOB',
        community: 'Koroduma-New Karu-MADUGU',
        state: 'Nasarawa',
        lga: 'Karu',
        projectType: 'Isolated Minigrids',
        puePotential: 5,
        enumerators: 0,
      },
      telecomSite('Infratel Ltd.', 'New Karu (Kabusu) KUPE', 'Nasarawa', 'Karu'),
      telecomSite('Infratel Ltd.', 'Tattara/Pandam/Panda/Kare', 'Nasarawa', 'Karu'),
      {
        developer: 'MMCL',
        community: 'New Karu (Kabusu) KUPE',
        state: 'Nasarawa',
        lga: 'Karu',
        projectType: 'Isolated Minigrids',
        puePotential: 0,
        enumerators: 0,
      },
      {
        developer: 'MMCL',
        community: 'Tattara/Pandam/Panda/Kare',
        state: 'Nasarawa',
        lga: 'Karu',
        projectType: 'Isolated Minigrids',
        puePotential: 0,
        enumerators: 0,
      },
      {
        developer: 'First Electric',
        community: 'Awe Township',
        state: 'Nasarawa',
        lga: 'Awe',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 12,
        enumerators: 3,
      },
      {
        developer: 'First Electric',
        community: 'Doma Road Community',
        state: 'Nasarawa',
        lga: 'Awe',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 8,
        enumerators: 2,
      },
      {
        developer: 'First Electric',
        community: 'Lafia South',
        state: 'Nasarawa',
        lga: 'Lafia',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 20,
        enumerators: 5,
      },
      {
        developer: 'MMCL',
        community: 'Lafia Central Market',
        state: 'Nasarawa',
        lga: 'Lafia',
        projectType: 'Mini Grids - Markets',
        puePotential: 15,
        enumerators: 4,
      },
      // Cross River - CEESOLAR
      {
        developer: 'CEESOLAR Energy',
        community: 'Akamkpa North',
        state: 'Cross River',
        lga: 'Akamkpa',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 18,
        enumerators: 4,
      },
      {
        developer: 'CEESOLAR Energy',
        community: 'Akamkpa South',
        state: 'Cross River',
        lga: 'Akamkpa',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 14,
        enumerators: 3,
      },
      {
        developer: 'CEESOLAR Energy',
        community: 'Ikom Township',
        state: 'Cross River',
        lga: 'Ikom',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 22,
        enumerators: 6,
      },
      {
        developer: 'CEESOLAR Energy',
        community: 'Oku Iboku',
        state: 'Cross River',
        lga: 'Ikom',
        projectType: 'Isolated Minigrids',
        puePotential: 10,
        enumerators: 2,
      },
      {
        developer: 'CEESOLAR Energy',
        community: 'Yala Central',
        state: 'Cross River',
        lga: 'Yala',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 16,
        enumerators: 4,
      },
      {
        developer: 'CEESOLAR Energy',
        community: 'Obubra Township',
        state: 'Cross River',
        lga: 'Obubra',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 12,
        enumerators: 3,
      },
      telecomSite('Infratel Ltd.', 'Obubra Telecom Site', 'Cross River', 'Obubra'),
      // Gombe - First Electric
      {
        developer: 'First Electric',
        community: 'Akko Central',
        state: 'Gombe',
        lga: 'Akko',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 25,
        enumerators: 6,
      },
      {
        developer: 'First Electric',
        community: 'Kumo',
        state: 'Gombe',
        lga: 'Akko',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 20,
        enumerators: 5,
      },
      {
        developer: 'First Electric',
        community: 'Gombe Metro South',
        state: 'Gombe',
        lga: 'Gombe',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 30,
        enumerators: 7,
      },
      telecomSite('Infratel Ltd.', 'Gombe Telecom Sites', 'Gombe', 'Gombe'),
      // Benue - Prado Power
      {
        developer: 'Prado Power Energy',
        community: 'Gboko Central',
        state: 'Benue',
        lga: 'Gboko',
        projectType: 'Agro-Processing Solar Hub',
        puePotential: 35,
        enumerators: 8,
      },
      {
        developer: 'Prado Power Energy',
        community: 'Mkar',
        state: 'Benue',
        lga: 'Gboko',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 18,
        enumerators: 4,
      },
      {
        developer: 'Prado Power Energy',
        community: 'Ushongo Township',
        state: 'Benue',
        lga: 'Ushongo',
        projectType: 'Agro-Processing Solar Hub',
        puePotential: 28,
        enumerators: 6,
      },
      {
        developer: 'Prado Power Energy',
        community: 'Adikpo',
        state: 'Benue',
        lga: 'Kwande',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 22,
        enumerators: 5,
      },
      {
        developer: 'Prado Power Energy',
        community: 'Kwande Central',
        state: 'Benue',
        lga: 'Kwande',
        projectType: 'Agro-Processing Solar Hub',
        puePotential: 30,
        enumerators: 7,
      },
      // Rivers - Darway Coast
      {
        developer: 'Darway Coast',
        community: 'Ahoada Township',
        state: 'Rivers',
        lga: 'Ahoada East',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 40,
        enumerators: 9,
      },
      {
        developer: 'Darway Coast',
        community: 'Omoku',
        state: 'Rivers',
        lga: 'Ahoada East',
        projectType: 'Isolated Minigrids',
        puePotential: 25,
        enumerators: 5,
      },
      {
        developer: 'Darway Coast',
        community: 'Degema Island',
        state: 'Rivers',
        lga: 'Degema',
        projectType: 'Isolated Minigrids',
        puePotential: 18,
        enumerators: 4,
      },
      {
        developer: 'Darway Coast',
        community: 'Ke',
        state: 'Rivers',
        lga: 'Degema',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 12,
        enumerators: 3,
      },
      // Edo - ACOB Lightning
      {
        developer: 'ACOB Lightning Technology',
        community: 'Egor Township',
        state: 'Edo',
        lga: 'Egor',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 22,
        enumerators: 5,
      },
      {
        developer: 'ACOB Lightning Technology',
        community: 'Ugbowo',
        state: 'Edo',
        lga: 'Egor',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 18,
        enumerators: 4,
      },
      {
        developer: 'ACOB Lightning Technology',
        community: 'Igueben',
        state: 'Edo',
        lga: 'Ovia South West',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 15,
        enumerators: 3,
      },
      {
        developer: 'ACOB Lightning Technology',
        community: 'Ekpon',
        state: 'Edo',
        lga: 'Ovia South West',
        projectType: 'Isolated Minigrids',
        puePotential: 10,
        enumerators: 2,
      },
      // Ondo - First Electric + ACOB
      {
        developer: 'First Electric',
        community: 'Ondo City South',
        state: 'Ondo',
        lga: 'Ondo',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 28,
        enumerators: 6,
      },
      {
        developer: 'ACOB Lightning Technology',
        community: 'Ondo City North',
        state: 'Ondo',
        lga: 'Ondo',
        projectType: 'Isolated Minigrids',
        puePotential: 20,
        enumerators: 4,
      },
      {
        developer: 'First Electric',
        community: 'Ore',
        state: 'Ondo',
        lga: 'Odigbo',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 24,
        enumerators: 5,
      },
      {
        developer: 'ACOB Lightning Technology',
        community: 'Odigbo Township',
        state: 'Ondo',
        lga: 'Odigbo',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 16,
        enumerators: 4,
      },
      {
        developer: 'First Electric',
        community: 'Irele Township',
        state: 'Ondo',
        lga: 'Irele',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 18,
        enumerators: 4,
      },
      // Kaduna - Hotspot Network
      telecomSite('Hotspot Network', 'Zango Kataf', 'Kaduna', 'Zangon Kataf'),
      telecomSite('Hotspot Network', 'Zonkwa', 'Kaduna', 'Zangon Kataf'),
      telecomSite('Hotspot Network', 'Kachia Town', 'Kaduna', 'Kachia'),
      // Kano - Hotspot Network
      telecomSite('Hotspot Network', 'Dambatta Township', 'Kano', 'Dambatta'),
      telecomSite('Hotspot Network', 'Bichi Town', 'Kano', 'Bichi'),
      // Abia - Darway Coast
      {
        developer: 'Darway Coast',
        community: 'Isuochi',
        state: 'Abia',
        lga: 'Umunneochi',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 20,
        enumerators: 4,
      },
      {
        developer: 'Darway Coast',
        community: 'Umunneochi Central',
        state: 'Abia',
        lga: 'Umunneochi',
        projectType: 'Isolated Minigrids',
        puePotential: 14,
        enumerators: 3,
      },
      {
        developer: 'Darway Coast',
        community: 'Ohafia Township',
        state: 'Abia',
        lga: 'Ohafia',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 18,
        enumerators: 4,
      },
      // Anambra
      {
        developer: 'CEESOLAR Energy',
        community: 'Onitsha West',
        state: 'Anambra',
        lga: 'Anambra West',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 25,
        enumerators: 5,
      },
      {
        developer: 'CEESOLAR Energy',
        community: 'Awka South Central',
        state: 'Anambra',
        lga: 'Awka South',
        projectType: 'Solar Hybrid Mini-Grid',
        puePotential: 30,
        enumerators: 6,
      },
      // FCT
      telecomSite('Hotspot Network', 'Kuje Township', 'FCT', 'Kuje'),
      telecomSite('Hotspot Network', 'Gwagwalada Town', 'FCT', 'Gwagwalada'),
      // Lagos
      telecomSite('Hotspot Network', 'Ikorodu North', 'Lagos', 'Ikorodu'),
      telecomSite('Hotspot Network', 'Ijede', 'Lagos', 'Ikorodu'),
      // Oyo
      telecomSite('Hotspot Network', 'Iseyin Township', 'Oyo', 'Iseyin'),
      telecomSite('Hotspot Network', 'Saki Town East', 'Oyo', 'Saki East'),
      // Jigawa
      telecomSite('Hotspot Network', 'Dutse Township', 'Jigawa', 'Dutse'),
      // Sokoto
      telecomSite('Hotspot Network', 'Sabon Birni Township', 'Sokoto', 'Sabon Birni'),
      // Kebbi
      telecomSite('Hotspot Network', 'Birnin Kebbi Central', 'Kebbi', 'Birnin Kebbi'),
      // Zamfara
      telecomSite('Hotspot Network', 'Gusau Township', 'Zamfara', 'Gusau'),
      // Katsina
      telecomSite('Hotspot Network', 'Katsina Township', 'Katsina', 'Katsina'),
      // Taraba
      telecomSite('Hotspot Network', 'Wukari Township', 'Taraba', 'Wukari'),
      // Plateau
      telecomSite('Hotspot Network', 'Wase Township', 'Plateau', 'Wase'),
      // Kogi
      telecomSite('Hotspot Network', 'Dekina Township', 'Kogi', 'Dekina'),
      // Kwara
      telecomSite('Hotspot Network', 'Baruten Township', 'Kwara', 'Baruten'),
      // Niger
      telecomSite('Hotspot Network', 'New Bussa', 'Niger', 'Borgu'),
      // Yobe
      telecomSite('Hotspot Network', 'Fika Township', 'Yobe', 'Fika'),
      // Ogun
      telecomSite('Hotspot Network', 'Igbooro', 'Ogun', 'Yewa North'),
    ],
  },

  {
    __component: 'projects-page.lga-modal-section' as const,
    subtitlePrefix: 'Project Data',
    subtitleStateSuffix: 'State',
    statLabelDevelopers: 'Developers',
    statLabelCommunities: 'Communities',
    statLabelPuePotential: 'PUE Potential',
    emptyTitle: 'No project data available for this LGA yet.',
    emptyBody: 'Data will populate once connected to the CFBF data API.',
    sourceLabel: 'Source: CFBF Geographical Distribution Data',
    closeLabel: 'Close',
    fallbackIcon: '🔌',
    columnHeads: [
      { label: 'Developer' },
      { label: 'Community' },
      { label: 'State' },
      { label: 'LGA' },
      { label: 'Project Type' },
      { label: 'PUE Potential' },
      { label: 'Enumerators' },
    ],
    projectTypeIcons: [
      { projectType: 'Solar Hybrid Mini-Grid', icon: '⚡' },
      { projectType: 'Isolated Minigrids', icon: '🔋' },
      { projectType: 'Solar as a Service for Telecom Towers', icon: '📡' },
      { projectType: 'Agro-Processing Solar Hub', icon: '🌾' },
      { projectType: 'Mini Grids - Markets', icon: '🏪' },
    ],
    // LGAModal.tsx:26-33 HERO_IMAGES — matched on the first project's type, with
    // the `default` row used when no type-specific image exists.
    heroImages: [
      {
        projectType: 'Solar as a Service for Telecom Towers',
        image:
          'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=1200&auto=format&fit=crop',
        image_alt_text: '',
      },
      {
        projectType: 'Agro-Processing Solar Hub',
        image:
          'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=1200&auto=format&fit=crop',
        image_alt_text: '',
      },
      {
        projectType: 'default',
        image:
          'https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=1200&auto=format&fit=crop',
        image_alt_text: '',
      },
    ],
  },

  {
    __component: 'projects-page.next-steps-section' as const,
    eyebrow: 'Next steps',
    headingPartOne: 'Explore the ',
    headingItalic: 'facility portal',
    links: [
      {
        eyebrow: 'About us',
        title: 'Who we are',
        description: 'Learn about our seed capital and mandates',
        href: '/about',
      },
      {
        eyebrow: 'Architecture',
        title: 'Learn how it works',
        description: 'Understand our blending process & structures',
        href: '/how-it-works',
      },
      {
        eyebrow: 'Impact',
        title: 'View our impact',
        description: 'Explore carbon targets and video stories',
        href: '/impact',
      },
    ],
  },
];
